name = "smart-traffic-comp2"
type = "javascript"

account_id = "c1685453fb2e13112e9d77bee8d37357"  # เอาจาก Cloudflare Dashboard
compatibility_date = "2025-08-06"
workers_dev = true

[site]
bucket = "./public"
entry-point = "."
