name = "smart-traffic-comp2"
account_id = "c1685453fb2e13112e9d77bee8d37357"
compatibility_date = "2025-08-06"
workers_dev = true

[build]
upload.format = "service-worker"

[site]
bucket = "./public"

